// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqD1cqGAZlzQz-lIwsqryt_DCJOTreg1c',
    appId: '1:191937777564:web:24da163908dda53039c259',
    messagingSenderId: '191937777564',
    projectId: 'authpart-691e4',
    authDomain: 'authpart-691e4.firebaseapp.com',
    storageBucket: 'authpart-691e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB94PKQrEzOz81pLXRXyx6jyatvBxrZZik',
    appId: '1:191937777564:android:3694e903584b862339c259',
    messagingSenderId: '191937777564',
    projectId: 'authpart-691e4',
    storageBucket: 'authpart-691e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlJATvL6ZGk3NLR-2FIen3jrpVaE3aXfI',
    appId: '1:191937777564:ios:ca5e84e58dede3c439c259',
    messagingSenderId: '191937777564',
    projectId: 'authpart-691e4',
    storageBucket: 'authpart-691e4.appspot.com',
    iosClientId: '191937777564-cs7bgj2tdmkphm2445q3578dfq270j1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlJATvL6ZGk3NLR-2FIen3jrpVaE3aXfI',
    appId: '1:191937777564:ios:ca5e84e58dede3c439c259',
    messagingSenderId: '191937777564',
    projectId: 'authpart-691e4',
    storageBucket: 'authpart-691e4.appspot.com',
    iosClientId: '191937777564-cs7bgj2tdmkphm2445q3578dfq270j1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
